version: '3'

services:
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: cache
    # volumes:
    #     - ./config/redis.conf:/redis.conf 
    # command: ["redis-server", "/redis.conf"]

  website:
    build: .
    container_name: flask
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "urlwarden.app:create_app()"
    env_file:
      - .env
    volumes:
      - .:/urlwarden
    ports:
      - 8000:8000
  
volumes:
  mongodbdata:
  redis:
